version: '3'
services:
  zincsearch:
    container_name: zincsearch
    image: public.ecr.aws/zinclabs/zincsearch:latest
    restart: always
    env_file:
      - .env
    ports:
      - '4080:4080'
    networks:
      - backend-network
    volumes:
      - zincsearch_data:/data

  server:
    container_name: email_searcher_api
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    networks:
      - backend-network
    volumes:
      - ./server:/app
    depends_on:
      - zincsearch

  web:
    container_name: email_searcher_interface
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./web
      dockerfile: Dockerfile
      target: development
    ports:
      - '5173:5173'
    volumes:
      - ./web:/app
    depends_on:
      - server

networks:
  backend-network:
    driver: bridge

volumes:
  zincsearch_data:
