version: '3'
services:
  zincsearch:
    container_name: zincsearch
    image: public.ecr.aws/zinclabs/zincsearch:latest
    restart: always
    environment:
      GIN_MODE: release
      ZINC_FIRST_ADMIN_USER: ${ZINC_FIRST_ADMIN_USER}
      ZINC_FIRST_ADMIN_PASSWORD: ${ZINC_FIRST_ADMIN_PASSWORD}
    networks:
      - backend-network
    volumes:
      - zincsearch_data:/data

  server:
    container_name: email_searcher_api
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - '3000:3000'
    environment:
      API_PORT: ${API_PORT}
      ZINCSEARCH_USERNAME: ${ZINCSEARCH_USERNAME}
      ZINCSEARCH_PASSWORD: ${ZINCSEARCH_PASSWORD}
      ZINCSEARCH_HOST: ${ZINCSEARCH_HOST}
      FRONT_END_URL: ${FRONT_END_URL}
    networks:
      - backend-network
    depends_on:
      - zincsearch

  web:
    container_name: email_searcher_interface
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: Dockerfile
      target: production
    ports:
      - '8080:8080'
    environment:
      VITE_API_URL: ${BACK_END_URL}
    depends_on:
      - server

networks:
  backend-network:
    driver: bridge

volumes:
  zincsearch_data:
